### PR TITLE
Fix typo in zettelkasten post

### PR DESCRIPTION
**Pull request by joshfarrant**
As you have an 'Edit on GitHub' link I thought I might as well fix the typo 😄

### CODE REVIEW

**Comment by spences10** [comment]
Awesome!

thanks 🙏

**Comment by spences10** [comment]
> As you have an 'Edit on GitHub' link I thought I might as well fix the typo 😄

That's exactly what it's there for, thank you so much 🙏

**Comment by joshfarrant** [comment]
This is definitely not the place for discussion of the post, but just wanted to say thanks for writing it! Was an interesting read and prompted me to finally check out Obsidian, which I'd heard of but never really understood. In the process of playing around with it now 😄

**Comment by spences10** [comment]
Glad it helped, if you need to chat catch me on Twitter 👍

**Pull request merged**
